use_frameworks!

platform :ios, '10.0'

target 'VTools_Example' do
  pod 'VTools', :path => '../'
  pod 'Device', :path => '../Device'
#  target 'VTools_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
